version: 0.0
os: linux

files:
  - source: build/libs/airbob-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/app
    overwrite: yes
  - source: scripts
    destination: /home/ubuntu/app/scripts
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
