services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      - DEBUG=true
    command: --redis.addr=redis://redis:6379
    depends_on:
      - redis
    networks:
      - redis-net

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    networks:
      - redis-net

  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
      - prometheus
    networks:
      - redis-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - redis-net

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./scripts:/scripts
    entrypoint: sh /scripts/entry.sh
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
