-- Debezium을 위한 유저 권한 설정
CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY 'dbz';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES, SHOW VIEW, EXECUTE ON *.* TO 'debezium'@'%';
FLUSH PRIVILEGES;

